name: doBeanGriefing
version: ${version}
main: com.simbeans.dobeangriefing.GriefingPlugin
description: Separates doMobGriefing into different events
author: sim-the-bean
api-version: ${apiversion}
load: STARTUP
bootstrapper: com.simbeans.dobeangriefing.GriefingPluginBootstrap
loader: com.simbeans.dobeangriefing.GriefingPluginLoader
defaultPerm: FALSE
permissions:
  dobeangriefing:
    description: Allows changing dobeangriefing rules.
    default: op
dependencies:
commands:
  dobeangriefing:
    description: Changes a beangriefing rule.
    aliases: [beangrief]
    permission: dobeangriefing
    permission-message: You do not have /<permission>
    usage: |
      /<command> <rule> true/false
      To show all valid rules, use /<command> without any arguments.